spring.application.name=crudSpringBootDemo

spring.datasource.url = jdbc:mysql://localhost:3306/student_crud_db_soft_delete
spring.datasource.username = root
spring.datasource.password = Omkar@15

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true