#spring.application.name=Demo
##paymentGateway.type=paytm
#paymentGateway.retry-count= 5

spring.application.name=Demo

payment-property.type = paytm
payment-property.retry-count=3
payment-property.enabled=true
payment-property.timeout=5000
